# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Card.create!(
  [
    {
      name: "アメトラ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "ametora.jpg",
      public_site_url: "https://kureka/ametora.com",
      age: 0.8,
      points: 0.9,
      miles: 0.3,
      annual_fee: 0,
    },
    {
      name: "ジャルカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "jaruka.jpg",
      public_site_url: "https://kureka/jaruka.com",
      age: 0.5,
      points: 0.5,
      miles: 0.8,
      annual_fee: 0.5,
    },
    {
      name: "オリポ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "oripo.jpg",
      public_site_url: "https://kureka/oripo.com",
      age: 0.3,
      points: 0.9,
      miles: 0.5,
      annual_fee: 0,
    },
    {
      name: "ラクカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "rakuka.jpg",
      public_site_url: "https://kureka/rakuka.com",
      age: 0.5,
      points: 0.8,
      miles: 0.3,
      annual_fee: 0,
    },
    {
      name: "ドコカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "dokoka.jpg",
      public_site_url: "https://kureka/rakuka.com",
      age: 0.5,
      points: 0.8,
      miles: 0.3,
      annual_fee: 0,
    },
    {
      name: "ミツカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "mituka.jpg",
      public_site_url: "https://kureka/mituka.com",
      age: 0.3,
      points: 0.5,
      miles: 0.3,
      annual_fee: 0,
    },
    {
      name: "ジェシカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "jesika.jpg",
      public_site_url: "https://jesika/mituka.com",
      age: 0.7,
      points: 0.6,
      miles: 0.4,
      annual_fee: 0.3,
    },
    {
      name: "レクカ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "rekuka.jpg",
      public_site_url: "https://kureka/rekuka.com",
      age: 0.5,
      points: 0.5,
      miles: 0.2,
      annual_fee: 0,
    },
    {
      name: "ジェーダブ",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "jedabu.jpg",
      public_site_url: "https://kureka/jedabu.com",
      age: 0.3,
      points: 0.7,
      miles: 0.6,
      annual_fee: 0,
    },
    {
      name: "オリゴール",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "origoru.jpg",
      public_site_url: "https://kureka/origo-ru.com",
      age: 0.7,
      points: 0.8,
      miles: 0.5,
      annual_fee: 0.7,
    },
    {
      name: "ジェーゴール",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "jegoru.jpg",
      public_site_url: "https://kureka/je-go-ru.com",
      age: 0.8,
      points: 0.5,
      miles: 0.7,
      annual_fee: 0.8,
    },
    {
      name: "ミツゴール",
      description: "ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。ここにはカードの簡単な説明文が入る予定です。",
      image_path: "mitugoru.jpg",
      public_site_url: "https://kureka/mitugo-ru.com",
      age: 0.8,
      points: 0.6,
      miles: 0.3,
      annual_fee: 0.8,
    }
  ]
)
